### ISSUE TITLE
Problema para añadir contenido externo

### ISSUE THREAD

**Issue by anitalmada** [CodigoSur/cyclope#102]
En la sección "Biblioteca Multimedia > Contenido Externo > Agregar" 
puedo completar perfectamente todos los campos pero cuando quiero ingresar la "Content URL" en lugar de habilitarme un campo o pop-up para poner una dirección, me abre el navegador de archivos como si fuera a cargar una foto o contenido multimedia.

Estoy usando Firefox en Ubuntu.

**Comment by Numerico** [comment]
Hola, gracias por notificarnos por este nuevo medio.
Sabes que lo intenté en varios sitios y siempre la URL del contenido me aparece como un campo de texto normal...
¿En qué sitio estás trabajando? ¿Tal vez podemos fijarnos ahí directamente?

**Comment by anitalmada** [comment]
Buenas, pido disculpas, me olvidé de ese dato: estoy trabajando en el sitio nuevo de Pillku.
No sé si serán de ayuda pero adjunto dos capturas de pantalla para que vean cómo se presenta el campo de URL de contenido. Además, descargué Chromium y lo probé ahí. Me pasa exactamente lo mismo.
![captura de pantalla de 2016-11-21 18-37-14](https://cloud.githubusercontent.com/assets/23624509/20501887/79459a8a-b01a-11e6-8050-e6a415c9d47e.png)
![captura de pantalla de 2016-11-21 18-38-06](https://cloud.githubusercontent.com/assets/23624509/20501886/793f4892-b01a-11e6-89eb-9d8f70f8bb90.png)

**Comment by mezcalit** [comment]
Reportaron desde GAMMA Ec. que les pasa lo mismo usando Windows y tanto con Firefox como con Chrome. Aquí mando algunos screens:

**Firefox**:

![error3](https://cloud.githubusercontent.com/assets/8534750/21428867/f5b2cbfa-c83a-11e6-920a-b42ee5749519.png)

![error2](https://cloud.githubusercontent.com/assets/8534750/21428875/0146a5d6-c83b-11e6-826a-864833fbb238.png)


**Chrome**:

![error1](https://cloud.githubusercontent.com/assets/8534750/21428883/075bc636-c83b-11e6-9379-5d82ab3c60be.png)

**Comment by mezcalit** [comment]
Y acá está el código fuente:

`
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es" >
<head>
<title>Añadir contenido externo | Administración de Cyclope</title>
<link rel="stylesheet" type="text/css" href="/media/admin/css/base.css" />


<link rel="icon" href="/media/cyclope/images/cyclope-icon.png" type="image/png">
<link rel="stylesheet" type="text/css" href="/media/admin/css/forms.css" />


<link rel="stylesheet" type="text/css" href="/media/cyclope/css/tabbed_collections.css" />



<link rel="stylesheet" type="text/css" media="screen" href="/media/cyclope/css/admin_tools_theming.css" />
<script type="text/javascript">window.__admin_media_prefix__ = "/media/admin/";</script>


<script type="text/javascript" src="/admin/jsi18n/"></script>
<link href="/media/markitup/skins/simple/style.css" type="text/css" media="screen" rel="stylesheet" />
<link href="/media/cyclope/markitup/sets/textile/style.css" type="text/css" media="screen" rel="stylesheet" />
<script type="text/javascript" src="/media/admin/js/core.js"></script>
<script type="text/javascript" src="/media/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/media/admin/js/jquery.min.js"></script>
<script type="text/javascript" src="/media/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/media/admin/js/actions.min.js"></script>
<script type="text/javascript" src="/media/cyclope/js/reuse_django_jquery.js"></script>
<script type="text/javascript" src="/media/cyclope/js/jquery-ui-1.8.4.custom.min.js"></script>
<script type="text/javascript" src="/media/admin/js/calendar.js"></script>
<script type="text/javascript" src="/media/admin/js/admin/DateTimeShortcuts.js"></script>
<script type="text/javascript" src="/media/markitup/ajax_csrf.js"></script>
<script type="text/javascript" src="/media/markitup/jquery.markitup.js"></script>
<script type="text/javascript" src="/media/cyclope/markitup/sets/textile/set.js"></script>
<script type="text/javascript" src="/media/admin/js/inlines.min.js"></script>
<script type="text/javascript" src="/media/cyclope/js/reuse_django_jquery.js"></script>
<script type="text/javascript" src="/media/cyclope/js/jquery.chainedSelect.js"></script>
<script type="text/javascript" src="/media/cyclope/js/less.min.js"></script>

<meta name="robots" content="NONE,NOARCHIVE" />
</head>


<body class="medialibrary-externalcontent  change-form">


<div id="container">

    
    
    <div id="header">
        <div id="branding">
        
<h1 id="site-name">Cyclope</h1>

        </div>
        
        <div id="user-tools">
            Te damos la Bienvenida
            <strong>manager</strong>.
            
                
                
                
                
                    <a href="/admin/password_change/">
                
                Cambiar contraseña</a> /
                
                
                    <a href="/admin/logout/">
                
                Cerrar sesión</a>
            
        </div>
        
        
    </div>
    
    
<div class="breadcrumbs">
<a href="/admin/">Inicio</a>
&rsaquo; <a href="/admin/medialibrary/">Medialibrary</a>
&rsaquo; <a href="/admin/medialibrary/externalcontent/">Contenidos externos</a>
&rsaquo; Agregar contenido externo
</div>

    

        

    
    <div id="content" class="colM">
        
        <h1>Añadir contenido externo</h1>
        

<div id="content-main">



<form enctype="multipart/form-data" action="" method="post" id="externalcontent_form"><div style='display:none'><input type='hidden' name='csrfmiddlewaretoken' value='7HtTGjhiOaqyHIuXwqyaehwmDUjSyGc4' /></div>
<div>






  <fieldset class="module aligned ">
    
    
    
        <div class="form-row field-name">
            
            
                <div>
                    
                    
                        <label for="id_name" class="required">Nombre:</label>
                        
                            <input id="id_name" type="text" class="vTextField" name="name" maxlength="250" />
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-slug">
            
            
                <div>
                    
                    
                        <label for="id_slug">Slug:</label>
                        
                            <input id="id_slug" type="text" class="vTextField" name="slug" maxlength="50" />
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-published">
            
            
                <div>
                    
                    
                        <input checked="checked" type="checkbox" name="published" id="id_published" /><label for="id_published" class="vCheckboxLabel">Publicar</label>
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-creation_date">
            
            
                <div>
                    
                    
                        <label for="id_creation_date_0" class="required">Fecha de creación:</label>
                        
                            <p class="datetime">Fecha: <input name="creation_date_0" value="21/12/2016" class="vDateField" type="text" id="id_creation_date_0" size="10" /><br />Hora: <input name="creation_date_1" value="14:25:04" class="vTimeField" type="text" id="id_creation_date_1" size="8" /></p><input type="hidden" name="initial-creation_date_0" value="21/12/2016" id="initial-id_creation_date_0" /><input type="hidden" name="initial-creation_date_1" value="14:25:04" id="initial-id_creation_date_1" />
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-allow_comments">
            
            
                <div>
                    
                    
                        <label for="id_allow_comments" class="required">Permitir comentarios:</label>
                        
                            <select name="allow_comments" id="id_allow_comments">
<option value="SITE" selected="selected">por defecto</option>
<option value="YES">habilitado</option>
<option value="NO">deshabilitado</option>
</select>
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-show_author">
            
            
                <div>
                    
                    
                        <label for="id_show_author" class="required">Mostrar autoría:</label>
                        
                            <select name="show_author" id="id_show_author">
<option value="AUTHOR">autoría</option>
<option value="USER">mostrar user si el campo autoría está vacío</option>
<option value="SITE" selected="selected">por defecto</option>
</select>
                        
                    
                    
                        <p class="help">Seleccione el campo que desea usar para mostrar como autoría de este contenido.</p>
                    
                </div>
            
        </div>
    
        <div class="form-row field-author">
            
            
                <div>
                    
                    
                        <label for="id_author">Autoría:</label>
                        
                            <select name="author" id="id_author">
<option value="" selected="selected">------</option>
</select><a href="/admin/cyclope/author/add/" class="add-another" id="add_id_author" onclick="return showAddAnotherPopup(this);"> <img src="/media/admin/img/icon_addlink.gif" width="10" height="10" alt="Añadir otro"/></a>
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-source">
            
            
                <div>
                    
                    
                        <label for="id_source">Fuente:</label>
                        
                            <select name="source" id="id_source">
<option value="" selected="selected">---------</option>
<option value="1">Tomada de Democracy Now</option>
<option value="2">Red de Mujeres para el Desarrollo</option>
<option value="3">Observatorio Ciudadano de la Comunicación</option>
</select><a href="/admin/cyclope/source/add/" class="add-another" id="add_id_source" onclick="return showAddAnotherPopup(this);"> <img src="/media/admin/img/icon_addlink.gif" width="10" height="10" alt="Añadir otro"/></a>
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-description">
            
            
                <div>
                    
                    
                        <label for="id_description">Descripción:</label>
                        
                            <textarea id="id_description" rows="10" cols="40" name="description" class="vLargeTextField"></textarea><script type="text/javascript">(function($) { $(document).ready(function() {  $("#id_description").markItUp(mySettings);   FileBrowserHelper.insertPicture("id_description");});})(jQuery);</script>
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-image">
            
            
                <div>
                    
                    
                        <label for="id_image">Imagen:</label>
                        
                            <input type="file" name="image" id="id_image" />
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-content_url">
            
            
                <div>
                    
                    
                        <label for="id_content_url" class="required">URL del contenido:</label>
                        
                            <input type="file" name="content_url" id="id_content_url" />
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-new_window">
            
            
                <div>
                    
                    
                        <input type="checkbox" name="new_window" id="id_new_window" /><label for="id_new_window" class="vCheckboxLabel">Abrir en ventana nueva</label>
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-skip_detail">
            
            
                <div>
                    
                    
                        <input type="checkbox" name="skip_detail" id="id_skip_detail" /><label for="id_skip_detail" class="vCheckboxLabel">Saltear vista detallada</label>
                    
                    
                </div>
            
        </div>
    
</fieldset>








    
<div class="inline-group" id="collections-categorization-content_type-object_id-group">
  <h2>Categorizaciones</h2>
<input type="hidden" name="collections-categorization-content_type-object_id-TOTAL_FORMS" value="0" id="id_collections-categorization-content_type-object_id-TOTAL_FORMS" /><input type="hidden" name="collections-categorization-content_type-object_id-INITIAL_FORMS" value="0" id="id_collections-categorization-content_type-object_id-INITIAL_FORMS" /><input type="hidden" name="collections-categorization-content_type-object_id-MAX_NUM_FORMS" value="1000" id="id_collections-categorization-content_type-object_id-MAX_NUM_FORMS" />


<div class="inline-related empty-form last-related" id="collections-categorization-content_type-object_id-empty">
  <h3><b>Categorización:</b>&nbsp;<span class="inline_label">#1</span>
    
    
  </h3>
  
  
    <fieldset class="module aligned ">
    
    
    
        <div class="form-row field-collection">
            
            
                <div>
                    
                    
                        <label for="id_collections-categorization-content_type-object_id-__prefix__-collection">Colección:</label>
                        
                            <select name="collections-categorization-content_type-object_id-__prefix__-collection" id="id_collections-categorization-content_type-object_id-__prefix__-collection">
<option value="" selected="selected">---------</option>
<option value="8">General</option>
<option value="1">Zonas</option>
</select>
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-category">
            
            
                <div>
                    
                    
                        <label for="id_collections-categorization-content_type-object_id-__prefix__-category" class="required">Categoría:</label>
                        
                            <select name="collections-categorization-content_type-object_id-__prefix__-category" id="id_collections-categorization-content_type-object_id-__prefix__-category">
<option value="39"> Nota Principal</option>
<option value="40"> Notas secundarias</option>
<option value="45"> Más noticias</option>
<option value="46"> Multimedia</option>
<option value="51"> Encuestas</option>
</select>
                        
                    
                    
                </div>
            
        </div>
    
</fieldset>

  
  <input type="hidden" name="collections-categorization-content_type-object_id-__prefix__-id" id="id_collections-categorization-content_type-object_id-__prefix__-id" />
  
</div>
</div>

<script type="text/javascript">
(function($) {
    $(document).ready(function() {
        var rows = "#collections-categorization-content_type-object_id-group .inline-related";
        var updateInlineLabel = function(row) {
            $(rows).find(".inline_label").each(function(i) {
                var count = i + 1;
                $(this).html($(this).html().replace(/(#\d+)/g, "#" + count));
            });
        };
        var reinitDateTimeShortCuts = function() {
            // Reinitialize the calendar and clock widgets by force, yuck.
            if (typeof DateTimeShortcuts != "undefined") {
                $(".datetimeshortcuts").remove();
                DateTimeShortcuts.init();
            }
        };
        var updateSelectFilter = function() {
            // If any SelectFilter widgets were added, instantiate a new instance.
            if (typeof SelectFilter != "undefined"){
                $(".selectfilter").each(function(index, value){
                  var namearr = value.name.split('-');
                  SelectFilter.init(value.id, namearr[namearr.length-1], false, "/media/admin/");
                });
                $(".selectfilterstacked").each(function(index, value){
                  var namearr = value.name.split('-');
                  SelectFilter.init(value.id, namearr[namearr.length-1], true, "/media/admin/");
                });
            }
        };
        var initPrepopulatedFields = function(row) {
            row.find('.prepopulated_field').each(function() {
                var field = $(this);
                var input = field.find('input, select, textarea');
                var dependency_list = input.data('dependency_list') || [];
                var dependencies = [];
                $.each(dependency_list, function(i, field_name) {
                  dependencies.push('#' + row.find('.form-row .field-' + field_name).find('input, select, textarea').attr('id'));
                });
                if (dependencies.length) {
                    input.prepopulate(dependencies, input.attr('maxlength'));
                }
            });
        };
        $(rows).formset({
            prefix: "collections-categorization-content_type-object_id",
            addText: "Agregar otro Categorización.",
            formCssClass: "dynamic-collections-categorization-content_type-object_id",
            deleteCssClass: "inline-deletelink",
            deleteText: "Eliminar",
            emptyCssClass: "empty-form",
            removed: updateInlineLabel,
            added: (function(row) {
                initPrepopulatedFields(row);
                reinitDateTimeShortCuts();
                updateSelectFilter();
                updateInlineLabel(row);
            })
        });
    });
})(django.jQuery);
</script>


    
<div class="inline-group" id="cyclope-relatedcontent-self_type-self_id-group">
  <h2>Contenidos Relacionados</h2>
<input type="hidden" name="cyclope-relatedcontent-self_type-self_id-TOTAL_FORMS" value="0" id="id_cyclope-relatedcontent-self_type-self_id-TOTAL_FORMS" /><input type="hidden" name="cyclope-relatedcontent-self_type-self_id-INITIAL_FORMS" value="0" id="id_cyclope-relatedcontent-self_type-self_id-INITIAL_FORMS" /><input type="hidden" name="cyclope-relatedcontent-self_type-self_id-MAX_NUM_FORMS" value="1000" id="id_cyclope-relatedcontent-self_type-self_id-MAX_NUM_FORMS" />


<div class="inline-related empty-form last-related" id="cyclope-relatedcontent-self_type-self_id-empty">
  <h3><b>Contenido Relacionado:</b>&nbsp;<span class="inline_label">#1</span>
    
    
  </h3>
  
  
    <fieldset class="module aligned ">
    
    
    
        <div class="form-row field-order">
            
            
                <div>
                    
                    
                        <label for="id_cyclope-relatedcontent-self_type-self_id-__prefix__-order">Order:</label>
                        
                            <input id="id_cyclope-relatedcontent-self_type-self_id-__prefix__-order" type="text" class="vIntegerField" name="cyclope-relatedcontent-self_type-self_id-__prefix__-order" />
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-other_type">
            
            
                <div>
                    
                    
                        <label for="id_cyclope-relatedcontent-self_type-self_id-__prefix__-other_type" class="required">Tipo de contenido:</label>
                        
                            <select name="cyclope-relatedcontent-self_type-self_id-__prefix__-other_type" id="id_cyclope-relatedcontent-self_type-self_id-__prefix__-other_type">
<option value="" selected="selected">------</option>
<option value="38">archivo</option>
<option value="27">artículo</option>
<option value="47">contacto</option>
<option value="39">contenido externo</option>
<option value="36">documento</option>
<option value="40">encuesta</option>
<option value="37">flash</option>
<option value="33">imagen</option>
<option value="34">pista de sonido</option>
<option value="31">página estática</option>
<option value="53">sindicación</option>
<option value="44">tema</option>
<option value="35">video</option>
</select>
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-other_object">
            
            
                <div>
                    
                    
                        <label for="id_cyclope-relatedcontent-self_type-self_id-__prefix__-other_object" class="required">objeto:</label>
                        
                            
<div class="GenericFKAdmin">
  <input class="vGenericFKAdminField" type="text" name="cyclope-relatedcontent-self_type-self_id-__prefix__-other_object" value="None" id="id_cyclope-relatedcontent-self_type-self_id-__prefix__-other_object">
  <div class="object-representation float-left"></div>
  <div class="current-object">
    <div class="search-widget">
        <label>Búsqueda</label>
        <a href="" class="related-lookup float-left" id="lookup_id_cyclope-relatedcontent-self_type-self_id-__prefix__-other_object" onclick="return showGenericRelatedObjectLookupPopup('cyclope-relatedcontent-self_type-self_id-__prefix__-other_type', this, '../../../');">
           <div class="search-widget-image"> <img src="/media/admin/img/selector-search.gif" width="16" height="16" alt="Lookup" /></div>
        </a>
    </div>
  </div>
  <div class="create-content-inlined-form">
  </div>
</div>

<script type="text/javascript">

var gfkSetNewValue = function( id_name,value){
    var obj = $("#" + id_name);
    obj.attr("newValue", value);
    obj.val(value);
}

var gfkEnsureRepresentation = function(id_name, ct_id){
    var obj = $("#" + id_name);
    if (obj.attr("value") !== obj.attr("newValue")){
        var obj_id = obj.attr("value");
        gfkSetNewValue(id_name, ct_id + "-" + obj.attr("value"));
        $.get("/related_admin/render_object/" + ct_id + "/" + obj_id + "/", function(data) {
            obj.siblings(".object-representation").html(data);
        });
    }
}

function showGenericRelatedObjectLookupPopup(ct_field, triggering_link, url_base) {
    var id_name = triggering_link.id.replace(/^lookup_/, '');
    // If ct is inline
    var indx_prefix = ct_field.indexOf("__prefix__")
    if (indx_prefix != -1){
        // get the index of the inline
        var index = triggering_link.id.split("lookup_id_")[1].slice(indx_prefix).split("-")[0];
        ct_field = ct_field.replace("__prefix__", index);
    }
    ct_select = document.getElementById('id_' + ct_field);

    var getCTId = function(ct_select){
        return ct_select.options[ct_select.selectedIndex].value;
    }
    var ct_id = getCTId(ct_select);
    var url = content_types[ct_id];

    // Yes this is insane but there isn't a robust way to fire an event by a
    // closing window that has a long ajax function inside without blocking
    setInterval(function() {gfkEnsureRepresentation(id_name, getCTId(ct_select)); }, 200);

    if (url != undefined) {
        triggering_link.href = url_base + url;
        var rv = showRelatedObjectLookupPopup(triggering_link);
        gfkSetNewValue(id_name, "");
        return rv;
    }
    return false;
}

$(".vGenericFKAdminField").css("display", "none");

var content_types = new Array();

    content_types[27] = 'articles/article/';

    content_types[36] = 'medialibrary/document/';

    content_types[47] = 'contacts/contact/';

    content_types[37] = 'medialibrary/flashmovie/';

    content_types[34] = 'medialibrary/soundtrack/';

    content_types[40] = 'polls/poll/';

    content_types[39] = 'medialibrary/externalcontent/';

    content_types[33] = 'medialibrary/picture/';

    content_types[44] = 'forum/topic/';

    content_types[31] = 'staticpages/staticpage/';

    content_types[53] = 'feeds/feed/';

    content_types[38] = 'medialibrary/regularfile/';

    content_types[35] = 'medialibrary/movieclip/';

    var htmlGFKCreateButton = function(html){
        return '<div class="gfk_create_title">Crear una nueva imagen</div>' + html + '<div class="gfk_create_button">Cargar</div>';
    };
    var ct_id = $("#id_cyclope-relatedcontent-self_type-self_id-__prefix__-other_type").val();
    if (ct_id){
        $.get("/api/create/", {"ct_id": ct_id}, function (data){
            if(data){
                $("#id_cyclope-relatedcontent-self_type-self_id-__prefix__-other_object").closest(".GenericFKAdmin").find(".create-content-inlined-form").html(htmlGFKCreateButton(data));
            }
        })
    }

    $( "body" ).delegate("fieldset select", "change", function(event){
        ct_field = event.currentTarget;
        if ($(ct_field).closest("fieldset").find(".GenericFKAdmin")){
            $.ajax({
                url: "/api/create/",
                data: {"ct_id": $(ct_field).val()},
                context: ct_field,
                success: function(data){
                    if(data){
                        $(this).closest("fieldset").find(".create-content-inlined-form").html(htmlGFKCreateButton(data));
                    }
                }
            });
        }
        return false;
    });

    $( "body" ).delegate( ".gfk_create_button", "click", function(event) {

        var fileInput = $(this).siblings().find("input[name*=simplified__-file]")[0];
        var name = $(this).siblings().find("input[name*=simplified__-name]").val();
        var file = fileInput.files[0];
        var formData = new FormData();
        var ct_id = $(this).closest("fieldset").find("select").val();
        formData.append('file', file);
        formData.append('name', name);
        formData.append('ct_id', ct_id);

        var xhr = new XMLHttpRequest();
        xhr.onload = function(){
            var jsonResponse = JSON.parse(this.responseText);
            $("#"+this.gfk_id).val(jsonResponse.obj_id);
            gfkEnsureRepresentation(this.gfk_id, jsonResponse.ct_id);
        }
        xhr.gfk_id = $(this).closest(".GenericFKAdmin").find(".vGenericFKAdminField").attr("id");
        xhr.open('POST', "/api/create/", true);
        xhr.setRequestHeader("X-CSRFToken", $("input[name=csrfmiddlewaretoken]").val());
        xhr.send(formData);

        return false; // prevent multiple events
    });
</script>

                        
                    
                    
                </div>
            
        </div>
    
</fieldset>

  
  <input type="hidden" name="cyclope-relatedcontent-self_type-self_id-__prefix__-id" id="id_cyclope-relatedcontent-self_type-self_id-__prefix__-id" />
  
</div>
</div>

<script type="text/javascript">
(function($) {
    $(document).ready(function() {
        var rows = "#cyclope-relatedcontent-self_type-self_id-group .inline-related";
        var updateInlineLabel = function(row) {
            $(rows).find(".inline_label").each(function(i) {
                var count = i + 1;
                $(this).html($(this).html().replace(/(#\d+)/g, "#" + count));
            });
        };
        var reinitDateTimeShortCuts = function() {
            // Reinitialize the calendar and clock widgets by force, yuck.
            if (typeof DateTimeShortcuts != "undefined") {
                $(".datetimeshortcuts").remove();
                DateTimeShortcuts.init();
            }
        };
        var updateSelectFilter = function() {
            // If any SelectFilter widgets were added, instantiate a new instance.
            if (typeof SelectFilter != "undefined"){
                $(".selectfilter").each(function(index, value){
                  var namearr = value.name.split('-');
                  SelectFilter.init(value.id, namearr[namearr.length-1], false, "/media/admin/");
                });
                $(".selectfilterstacked").each(function(index, value){
                  var namearr = value.name.split('-');
                  SelectFilter.init(value.id, namearr[namearr.length-1], true, "/media/admin/");
                });
            }
        };
        var initPrepopulatedFields = function(row) {
            row.find('.prepopulated_field').each(function() {
                var field = $(this);
                var input = field.find('input, select, textarea');
                var dependency_list = input.data('dependency_list') || [];
                var dependencies = [];
                $.each(dependency_list, function(i, field_name) {
                  dependencies.push('#' + row.find('.form-row .field-' + field_name).find('input, select, textarea').attr('id'));
                });
                if (dependencies.length) {
                    input.prepopulate(dependencies, input.attr('maxlength'));
                }
            });
        };
        $(rows).formset({
            prefix: "cyclope-relatedcontent-self_type-self_id",
            addText: "Agregar otro Contenido Relacionado.",
            formCssClass: "dynamic-cyclope-relatedcontent-self_type-self_id",
            deleteCssClass: "inline-deletelink",
            deleteText: "Eliminar",
            emptyCssClass: "empty-form",
            removed: updateInlineLabel,
            added: (function(row) {
                initPrepopulatedFields(row);
                reinitDateTimeShortCuts();
                updateSelectFilter();
                updateInlineLabel(row);
            })
        });
    });
})(django.jQuery);
</script>









<script type="text/javascript">
//<![CDATA[
function setup_chainedSelect_for_categorization(i) {
    $("#id_collections-categorization-content_type-object_id-"+ i +"-category").chainedSelect({
        parent: '#id_collections-categorization-content_type-object_id-'+ i +'-collection',
        url: "/collection_categories_json",
        value: 'category_id',
        label: 'category_name'
    });
};

jQuery(document).ready(function($){
  $("select[id^='id_collections-categorization-content_type-object_id-'][id$='-category']").each(function(i, sel){
        setup_chainedSelect_for_categorization(i);
  });

  $("#collections-categorization-content_type-object_id-group .add-row a").click(
    function(){
      i = $("select[id^='id_collections-categorization-content_type-object_id-'][id$='-category']").length - 2
      setup_chainedSelect_for_categorization(i);
    });
});
//]]>
</script>


<script type="text/javascript">
//<![CDATA[
function setup_chainedSelect_for_relatedcontent(i) {
    $('#id_cyclope-relatedcontent-self_type-self_id-'+ i +'-other_id').chainedSelect({
        parent: '#id_cyclope-relatedcontent-self_type-self_id-'+ i +'-other_type',
        url: "/objects_for_ctype_json",
        value: 'object_id',
        label: 'verbose_name'
    });
};

jQuery(document).ready(function($){
  $("select[id^='id_cyclope-relatedcontent-self_type-self_id-'][id$='-other_id']").each(function(i, sel){
        setup_chainedSelect_for_relatedcontent(i);
  });

  $("#cyclope-relatedcontent-self_type-self_id-group .add-row a").click(
    function(){
      i = $("select[id^='id_cyclope-relatedcontent-self_type-self_id-'][id$='-other_id']").length - 2
      setup_chainedSelect_for_relatedcontent(i);
    });
});
//]]>

</script>






<div class="submit-row">
<input type="submit" value="Guardar" class="default" name="_save" />


<input type="submit" value="Grabar y añadir otro" name="_addanother"  />
<input type="submit" value="Grabar y continuar editando" name="_continue" />
</div>



   <script type="text/javascript">document.getElementById("id_name").focus();</script>




<script type="text/javascript">
(function($) {
    var field;


})(django.jQuery);
</script>


</div>
</form></div>







<script type="text/javascript">
//<![CDATA[
function setup_chainedSelect_for_categorization(i) {
    $("#id_collections-categorization-content_type-object_id-"+ i +"-category").chainedSelect({
        parent: '#id_collections-categorization-content_type-object_id-'+ i +'-collection',
        url: "/collection_categories_json",
        value: 'category_id',
        label: 'category_name'
    });
};

jQuery(document).ready(function($){
  $("select[id^='id_collections-categorization-content_type-object_id-'][id$='-category']").each(function(i, sel){
        setup_chainedSelect_for_categorization(i);
  });

  $("#collections-categorization-content_type-object_id-group .add-row a").click(
    function(){
      i = $("select[id^='id_collections-categorization-content_type-object_id-'][id$='-category']").length - 2
      setup_chainedSelect_for_categorization(i);
    });
});
//]]>
</script>


<script type="text/javascript">
//<![CDATA[
function setup_chainedSelect_for_relatedcontent(i) {
    $('#id_cyclope-relatedcontent-self_type-self_id-'+ i +'-other_id').chainedSelect({
        parent: '#id_cyclope-relatedcontent-self_type-self_id-'+ i +'-other_type',
        url: "/objects_for_ctype_json",
        value: 'object_id',
        label: 'verbose_name'
    });
};

jQuery(document).ready(function($){
  $("select[id^='id_cyclope-relatedcontent-self_type-self_id-'][id$='-other_id']").each(function(i, sel){
        setup_chainedSelect_for_relatedcontent(i);
  });

  $("#cyclope-relatedcontent-self_type-self_id-group .add-row a").click(
    function(){
      i = $("select[id^='id_cyclope-relatedcontent-self_type-self_id-'][id$='-other_id']").length - 2
      setup_chainedSelect_for_relatedcontent(i);
    });
});
//]]>

</script>








<script type="text/javascript">
//<![CDATA[

jQuery(document).ready(function($){

    var current_collection = null;

    var select_collection = function (collection){
        $("select[id^='id_collections-categorization-content_type-object_id-'][id$='-collection']")
            .each(function(){
                if (!collection){
                    $(this).closest('.inline-related').hide();
                }
                else if (this.value != collection){
                    $(this).closest('.inline-related').hide();
                }
                else{
                    $(this).closest('.inline-related').show()
                }
            });
        current_collection = collection;

        $('li[id^=id_collections-tab-]').each(function(i){
            $(this).removeClass('current-tab')
        });

        $('#id_collections-tab-'+ collection).addClass('current-tab');
    }

    
    var initial = $("select[id^='id_collections-categorization-content_type-object_id-'][id$='-collection']").val();
    

    
    var initial_category = null;
    

    $('#collections-categorization-content_type-object_id-group h2').after('<div id="collection-tabs-container"><ul id="collection-tabs-list"></ul></div>');

    $('#id_collections-categorization-content_type-object_id-__prefix__-collection option')
        .each(function(i){
            if (this.text.match(/-+/g) != this.text){
                var collection = this.value
                var link_id = "id_collections-tab-"+ collection //$(this).parent().attr('id')
                $('#collection-tabs-list').append('<li class="tab" id="'+link_id+'"><a href="javascript:void(0)" >'+this.text+'</a></li>');
//                $('#collections-categorization-content_type-object_id-group h2').after('<span class="collection-tab" ><a href="javascript:void(0)" id="'+link_id+'" >'+this.text+'</a></span>');

                $("#"+link_id).click(function(){
                    select_collection(collection);
                });
            }
        });

    $('#collections-categorization-content_type-object_id-group > .add-row a')
        .click(function(){
            if (!current_collection){
                alert("Primero debe serleccinar una colección.")
            }
            else{
                i = $("select[id^='id_collections-categorization-content_type-object_id-'][id$='-collection']").length - 2
                sel = '#id_collections-categorization-content_type-object_id-'+i+'-collection'
                $(sel).val(current_collection);
                select_collection(current_collection);
                $(sel).change();
                $(sel).parents(".collection").hide();
                if (initial_category!=null){
                  cat_sel = '#id_collections-categorization-content_type-object_id-'+i+'-category';
                  $(cat_sel).val(initial_category);
                }
            }
        });

    select_collection(initial);
    $(".dynamic-collections-categorization-content_type-object_id .collection").hide();
    
    if (initial_category != null){
// check if the initial_category is already selected (usually true after a form validation error)
      category_selections = $("select[id^='id_collections-categorization-content_type-object_id-'][id$='-category']").filter(":visible");
      already_selected = false;
      $(category_selections).each(function(i,sel){
        if ($(sel).val() == initial_category){
          already_selected = true
        }
      });
      if (!already_selected){
        $("#collections-categorization-content_type-object_id-group .add-row a").trigger("click");
      }
   }

})
//]]>
</script>




        
        <br class="clear" />
    </div>
    

     <div id="footer">Desarrollado por <a href="http://www.codigosur.org" target="_blank">Código Sur</a></div> 
</div>


</body>
</html>
`

**Comment by Numerico** [comment]
Bueno, eféctivamente en el fuente que compartieron podemos ver que el input viene como file en HTML:
`
<label for="id_content_url" class="required">URL del contenido:</label>
<input type="file" name="content_url" id="id_content_url" />
`
Esto no es asi en nuestros navegadores:
`
<label for="id_content_url" class="required">URL del contenido:</label>
<input id="id_content_url" class="vTextField" name="content_url" maxlength="100" type="text">
`
Ahora, ¿por qué esta diferencia?

**Comment by santiagogarciagago** [comment]
Compas, no es un bug ni depende de los navegadores. 

Cuando se desarrolló VotoInformado (04/2015) nos dimos cuenta que era un sitio que al contar con diferentes usuarios cuando seleccionaban subir archivos multimedia accedian al Visor de Archivos completo, por lo que podían borrar/editar archivos que subían otros usuarios/as. Para evitar eso con Nico se pensó que:

>  _"debería mostrar un widget simple para subir los files de MediaLibrary, **para cualquier usuario que no sea superuser**"_. 

Se implementó la primera parte, pero quedó pendiente 

>  _"después implementaremos que esto sea un permiso específico"_. 

Este es el commit: 

#https://github.com/CodigoSur/cyclope/commit/cad3b306362e018f5c38ff1eefecc03e54cae4e9

La forma sencilla para solucionarlo ahora es dar permisos de superuser a esos usuarios. Lo siguiente sería crear esa opción para activar/desactivar el widget. 

Abrazo!
