### ISSUE TITLE
Ordenar categorizaciones O(n) cuelga con muchos registros

### ISSUE THREAD

**Issue by Numerico** [CodigoSur/cyclope#103]
Si una Categoría tiene demasiadas categorizaciones, ordenarlas resulta demasiado ineficiente y cuelga el servidor.
¿Buscar algoritmo de actualización más eficiente?

**Comment by Numerico** [comment]
El error es **504 Gateway Time-out** de _nginx_

Actualizar todos los registros toma un tiempo excesivo, por lo cual el proceso Django no retorna.
Una idea es implementar paginación, pero ésto no necesariamente resolvería el que _haya que actualizar el campo order todos los registros_ al mover de posición a uno de ellos.

Otra es pensar en optimizar la consulta a la DB.

O reemplazar el campo **order** por un algoritmo más eficiente.

**Comment by mezcalit** [comment]
Me parece que buscar una alternativa más eficientes puede ser la mejor práctica. +1

**Comment by spiccinini** [comment]
Hola! Creo que lo mejor es que el campo order sea de tipo float (FloatField) y cuando se hace una inserción en el medio (o un cambio de orden moviendo un elemento) que el valor del order se tome como la mitad entre el anterior y el siguiente.

Ejemplo:
```
1 foo
2 bar
3 baz
```
movemos `baz` entre `foo` y `bar`:

```
1 foo
1.5 baz
2 bar
```
