### ISSUE TITLE
Relacionado con (HTML) - El atributo de la etiqueta de elemento hay que referirse a un control no oculta formulario

### ISSUE THREAD

**Issue by MauHernandez** [CodigoSur/cyclope#11]
Error: The for attribute of the label element must refer to a non-hidden form control. En los formularios de comentarios se observa este error específicamente en la parte 
`
<label **for="id_captcha_1"** class="control-label  requiredField">`

**Comment by Numerico** [comment]
esto no es un error, no repercute en el usuario ni es visible para nadie mas que para un 'validador de html'. me parece insignificante.
además, es código de una aplicación integrada que habría que sobrescribir para modificar, lo cual no creo que valga la pena.
-1 a darle importancia a este tipo de cosas

**Comment by MauHernandez** [comment]
De acuerdo
