### ISSUE TITLE
Errores al Insertar contenidos con MediaWidget

### ISSUE THREAD

**Issue by santiagogarciagago** [CodigoSur/cyclope#111]
Buenas, estuve probando el plugin para insertar contenido dentro del texto y hay varios errores, pero depende mucho del navegador que se use el error es uno u otro (con S.O. Debian 8 / Firefox 45.6.0 / Chrome 55.0.2883.87 (64-bit)). Pongo el detalle para que alguien más pruebe en otras condiciones, hay un issue con Macintosh, quizás es algo como esto. 

**General**
El widget al abrir y cerrar queda como en el estado previo. Si subes una imagen, al abrir para subir el video mantiene el título del anterior. No pasaría nada, a no ser que haya un error, no hay forma de "reiniciar" el widget, sólo recargando la página. 

Un error como subir un video con "ñ" o símbolos no autorizados. No slugea los nombres de archivo y tira error con caracteres no válidos
```
UnicodeEncodeError at /media_widget/embed/create
'ascii' codec can't encode character u'\xf1' in position 79: ordinal not in range(128)
```

**Imagen**

Inserta el paréntesis final la descripción que no es campo obligatorio como title de la imagen y por eso queda vacio muchas veces y no muesta la imagen. Antes ahí se colocaba (alt_text). Habría que poner mejor el título o si no hya descripción poner alt_text. 

`!(left)/media/pictures/2017/01/10686.png**()**!`

**Audios**

Firefox 
Sin problema en audios mp3. 
Error en con los ogg ya que se crean con un mime/type video/ogg y tira: 
`¡video/ogg no es un tipo de Audio válido!`

Chrome
Bien con los ogg, error con mp3
`¡audio/mp3 no es un tipo de Audio válido!`

**Video**  

Sin problemas, sólo faltaría una regla css para que si el video es my ancho no rompa el layout: 

`.text video {max-width: 100%;}`

**PDF**

Firefox 
Probado con varios PDF que en terminal tienen un mime/type correcto de aplicación/pdf pero al subir dicen: 
`¡binary/octet-stream no es un tipo de PDF válido!`

Chrome
Sin problema. 

General
Sugiero que en vez de un ancho fijo (550px) se coloque width='100%'

**Flash**

Firefox y Chrome
Probado con varios SWF y tira el error: 
`¡application/vnd.adobe.flash.movie no es un tipo de Flash válido!`

**Comment by Numerico** [comment]
Separado en un issue para cada problema:

- ~~texto alternativo de imagenes~~: #119 
- ~~caracteres unicode (ñ)~~: #117 
- ~~delay de actualizacion del widget~~: #118
- errores de validacion de mime/type: #122
- mejoras de estilos: ~~#120~~ y #122

**Comment by anepcr** [comment]
**Colocar buscador en la biblioteca a lo interno de las notas **

Hola, me parece necesario colocar un buscador en la biblioteca (a lo interno de las notas), ya que a la hora de poner una imagen para una nota no aparece ningún buscador se hace complicado tener que buscar la foto que ya esta en el servidor, ya que se debe pasar pagina por pagina `para ver cual es la foto.

![image](https://cloud.githubusercontent.com/assets/25779320/22950223/82b746c0-f2ca-11e6-9595-27ac06544e9a.png)

**Comment by Numerico** [comment]
Closed por error
