### ISSUE TITLE
Serio problema de SPAM en comentarios de Cyclope

### ISSUE THREAD

**Issue by santiagogarciagago** [CodigoSur/cyclope#112]
En estos días está llegando mucho spam a Radios Libres por lo que moderé los comentarios, pero alguien que comenta regularmente me dijo que le llegaba mucho spam desde la web y me puse a revisar. Como saben los comentarios tienen la opción de suscribirse para que te notifiquen cuando hay respuestas. Estuve probando y: 

- Problema **ALTA** prioridad: las notificaciones de los mensajes llegan aunque tengas moderados los comentarios. Es decir, activo la moderación, los spamer responden a comentarios y eso les llega por correo a quienes escribieron si se suscribieron para recibir notificaciones. Luego yo borro los mensajes y no se publican en la web, pero el email con el spam está llegando a las personas que comentaron. 

- Problema **baja** prioridad: sólo funciona con el comentario principal. Si yo respondo a un comentario y me suscribo, cuando alguien me responda a mi, no me notifican, sólo al que creo el comentario original.

**Comment by mezcalit** [comment]
Confirmo, hoy han reportando desde El Salvador lo mismo. Creo que este ticket debería pasar a ser prioridad.

**Comment by Numerico** [comment]
El código que se está abusando es exactamente aquí
[cyclope/apps/custom_comments/models.py#L64](https://github.com/CodigoSur/cyclope/blob/development/cyclope/apps/custom_comments/models.py#L64)

        # Send mail to suscribed users of the tree path
        comments = CustomComment.objects.filter(id=self.root_path, subscribe=True)
        if comments:
            messages = [(subject, message, settings.DEFAULT_FROM_EMAIL,
                         [comment.userinfo["email"]]) for comment in comments]
            send_mass_mail(messages, fail_silently=True)

Estamos siendo muy permisivos, pues enviamos correos a todos los suscritos apenas alguien hace un nuevo comentario. Este comportamiento está siendo abusado

**Comment by Numerico** [comment]
Desde ayer, hemos deshabilitado momentáneamente el envío de correos a los suscriptores de los comentarios en todos los sitios. 
Solamente el envío de la notificación a los Administradores sigue habilitado.
Estamos trabajando en una propuesta que involucre la moderación de comentarios para estas notificaciones.

**Comment by Numerico** [comment]
Respecto al *'*Problema baja prioridad**'
No es lo que veo en el código, sino que a todos los sucritos del hilo.
Si no anda así, favor abrir otro issue.
