### ISSUE TITLE
Compartir en redes sociales está deprecado y sigue apareciendo en Setting de CyclopeCMS

### ISSUE THREAD

**Issue by mezcalit** [CodigoSur/cyclope#113]
El sistema anterior de compartir en redes sociales se configuraba desde Settings en CyclopeCMS en versiones anteriores. Esta opción ha sido deprecada hace tiempo, sin embargo sigue apareciendo en el admin confundiendo a las personas usuarias. 

![seleccion_727](https://cloud.githubusercontent.com/assets/8534750/22530498/6f1557de-e8a1-11e6-8207-806730cccc0a.png)

**Comment by Numerico** [comment]
Relacionado al #75
