### ISSUE TITLE
Media Widget: caracteres unicode en nombres de archivos da error

### ISSUE THREAD

**Issue by Numerico** [CodigoSur/cyclope#117]
Un error como subir un video con "ñ" o símbolos no autorizados. No slugea los nombres de archivo y tira error con caracteres no válidos

    UnicodeEncodeError at /media_widget/embed/create
    'ascii' codec can't encode character u'\xf1' in position 79: ordinal not in range(128)

**Comment by Numerico** [comment]
@santiagogarciagago no estoy pudiendo reproducir este issue
¿cuándo ves el error exactamente? queda la página en error 500? el widget? en  la consola javascript?
en local estoy pudiendo subir archivos con caracteres unicode, los cuales se insertan tal cual, ej.
`!(left)/media/pictures/2017/02/ñuñoa.jpg(alt_text)!`
en todo caso estoy de acuerdo con _slugificarlo_.

**Comment by Numerico** [comment]
Closed in  ef8af3b

**Comment by santiagogarciagago** [comment]
El problema se dio con los videos, no con las fotos. Pero sí, creo que mejor que quede "slugificado".
