### ISSUE TITLE
No funciona ver comentarios más nuevos en primer lugar

### ISSUE THREAD

**Issue by santiagogarciagago** [CodigoSur/cyclope#129]
Dejó de andar en la versión development esta funcionalidad incorporada en el commit [d7fea8c](https://github.com/CodigoSur/cyclope/commit/9d4d5c3f537f0547100013d0ae2e598d316e19d2) para que los comentarios más nuevos se vean en la parte de arriba del listado de comentarios. El script está en el template adecuado pero no funciona.

jQuery(document).ready(function(){
            // sort comments from newest to oldest
            var list = $('#user_comments');
            var listItems = list.children('ul');
            list.append(listItems.get().reverse());
        });

**Comment by Numerico** [comment]
No me gusta mucho reordenar los comentarios con jQuery...
¿No sería mejor que vengan en este orden desde la vista de Django?
¿O hay algún caso en que queramos el orden inverso?

**Comment by santiagogarciagago** [comment]
Fue un debate que tuvimos y acordamos que tiene lógica que los comentarios muestren los más nuevos en la parte de arriba y creo que la forma más sencilla que se pensó en ese momento fue esa y, quizás, se dejó así para que pisando el template, si alguien los quisiera al revés, volvieran al estado original. Pero creo que podrían venir desde django ordenados ascendentemente.

**Comment by santiagogarciagago** [comment]
Problema en template local por un 

`<div class="comments">` 

el list.html
