### ISSUE TITLE
filebrowser debe ser actualizado o deprecado

### ISSUE THREAD

**Issue by Numerico** [CodigoSur/cyclope#142]
para el update a 1.9 momentaneamente deshabilitamos filebrowser.
la version que usamos es https://github.com/spiccinini/django-filebrowser-no-grappelli-and-uploadify/tree/master/filebrowser (2015)
deriva de https://github.com/alexvasi/django-filebrowser-no-grappelli-and-uploadify (2011)
y ésta de https://github.com/smacker/django-filebrowser-no-grappelli (2017)
(con pasos intermedios)
es a ésta última versión que tal vez podríamos actualizar,
La otra opción es abandonar Filebrowser (la interfaz usa popups, tiene javascripts problemáticos...), el cual podría ser reemplazado por el MediaWidget.

**Comment by santiagogarciagago** [comment]
En el día a día tener un mínimo filebrowser es bastante útil. Quizás podría ser algo de sólo lectura, pero tendríamos que seguir rodando el mediawidget y trabajando más con él a ver si lo suple. Para eso sería urgente que el mediawidget tenga buscador, sino toca ir por la Biblioteca Multimedia a buscar y luego pasar páginas para encontrar la imagen buscada.

**Comment by Numerico** [comment]
@santiagogarciagago 
Si, tambien es util por ej para las versiones, o tendremos que buscar otra solucion para eso.
La idea si seria eventualmente unirla con la ventana multimedia, y si, vamos por el buscador.
