### ISSUE TITLE
mejorar la guía de instalación

### ISSUE THREAD

**Issue by mezcalit** [CodigoSur/cyclope#146]
La guía de instalación está desactualizada o no es lo suficientemente clara. Muchas personas usarias de GNU/Linux han reportado algún tipo de problemas en la instalación repetidamente. Por eso es necesario actualizar la guía para facilitar la instalación por personas sin conocimienos específicos de python/django.

**Comment by mezcalit** [comment]
https://github.com/CodigoSur/cyclope/wiki/Gu%C3%ADa-de-instalaci%C3%B3n

**Comment by klhernandez42** [comment]
Una buena, adición podrian ser la grabada de escritorio de la instalacion y screenshot del proceso... voy a ver si luego desintalo y vuelvo a grabar para que quede en linux mint que va siendo para ubunteros y arch linux...

**Comment by Numerico** [comment]
yo quisiera que la url fuera m(ascii) limpia https://github.com/CodigoSur/cyclope/wiki/Guia-de-instalacion

**Comment by mezcalit** [comment]
Numérico, es un tema a revisar por aquello de los acentos en el texto. Por lo pronto puede escribirse con tilde https://github.com/CodigoSur/cyclope/wiki/Guía-de-instalación y funciona bien y es más lindo visualmente que la otra.

**Comment by klhernandez42** [comment]
Adaptacion, redacción y testeo de la guia de instalación finalizado. :100:  

¿Si alguien puede tratar de se guir el paso a paso? 
y contar la experiencia si es exitoso igual por favor reportarlo. :+1:
