### ISSUE TITLE
Redefinir las categorizaciones

### ISSUE THREAD

**Issue by ortegadaniel** [CodigoSur/cyclope#147]
Redefinir el sistema de categorizaciones, para que pueda ser autocompletable. (CategorizationForm) 
:+1:

**Comment by Numerico** [comment]
las [relaciones genericas en el admin](https://docs.djangoproject.com/en/1.11/ref/contrib/contenttypes/#generic-relations-in-admin) como inlines usan popups y javascripts del terror.
la idea sería redefinirlas con algo más usable como un autocomplete
