### ISSUE TITLE
Carousel  view options in menu item

### ISSUE THREAD

**Issue by MauHernandez** [CodigoSur/cyclope#21]
Las opciones de vista en el menu items menu para la vista de tipo carousel de categoria no se renderizan de manera correcta el 100% de las veces lo que genera errores al momento de llevar las opciones a la capa de persistencia de data, despues de varios intentos aleatorios es posible en estos casos guardar la data. No se arroja error de ningun tipo via consola.

**Comment by Numerico** [comment]
Hay un error en los view options en general, no se pueden editar. 
Por ahora hay que Eliminar el MenuItem o RegionView y crear otro...
