### ISSUE TITLE
Sacar del admin estas views option

### ISSUE THREAD

**Issue by ortegadaniel** [CodigoSur/cyclope#25]
![captura de pantalla de 2016-08-18 17 29 40](https://cloud.githubusercontent.com/assets/20782611/17794062/7ec1fcde-6569-11e6-8aab-f16e7ef313dd.png)

Sacar la opción contenido y las views option

**Comment by MauHernandez** [comment]
Tambien en site search
![image](https://cloud.githubusercontent.com/assets/13241119/17833197/588a9ca2-66e4-11e6-9904-466db10f3250.png)

**Comment by Numerico** [comment]
Respecto a los contenidos, quedan referenciados en el #26
