### ISSUE TITLE
sindicación bloquea la carga de la web cuando no responde el rss

### ISSUE THREAD

**Issue by mezcalit** [CodigoSur/cyclope#30]

**Comment by Numerico** [comment]
No se reproduce ni en local ni en producción
La base es **feedparser==5.1** [(En PyPi)](https://pypi.python.org/pypi/feedparser/5.2.1) [En GitHub](https://github.com/kurtmckee/feedparser)
En caso que el _feed no exista_, retorna un objeto vacío aquí https://github.com/kurtmckee/feedparser/blob/f1dd1bb923ebfe6482fc2521c1f150b4032289ec/feedparser/api.py#L199
Lo que hace Cyclope es mostrar el título sin Entries
