### ISSUE TITLE
re-escribir print.css

### ISSUE THREAD

**Issue by mezcalit** [CodigoSur/cyclope#33]
es importante testear el print.css y ver que esté funcionando correctamente.

**Comment by MauHernandez** [comment]
Resuelto en commit  c05cbb2c6c86f29967cc04f392705dab81ffe339
Esperando por pull request para cerrar @mezcalit

**Comment by Numerico** [comment]
Documento PDF ilegible por márgen derecho

**Comment by MauHernandez** [comment]
Saludos @Numerico podrias decirme en que situacion? Te envio un capture de ejemplo, como muchos que probe en su momento y era legible! Quizas pase algo por alto, por eso te pido el ejemplo. 

Saludos 

![image](https://cloud.githubusercontent.com/assets/13241119/18994832/9b094e38-86f7-11e6-9d8f-d416575d7b67.png)
