### ISSUE TITLE
Cambiar Padre x Madre en traducciones

### ISSUE THREAD

**Issue by santiagogarciagago** [CodigoSur/cyclope#45]
En las categorías o menús cambiar la traducción para mejorar lenguaje inclusivo.

**Comment by mezcalit** [comment]
Aquí tienes los screens de lo que dice Santiago. 

![padre1](https://cloud.githubusercontent.com/assets/8534750/18396865/f0796a68-7682-11e6-9ba1-e90dd3ea85c1.png)

![padre2](https://cloud.githubusercontent.com/assets/8534750/18396863/eca4435e-7682-11e6-9fab-dfbeb599aa99.png)

No está resuelto con la modificación del archivo .po en cyclope/locale/es/LC_MESSAGES

**Comment by Numerico** [comment]
Cambiado en esos dos lugares. Favor comentar si se ven más Padres para reabrirlo.
