### ISSUE TITLE
paginación en móviles

### ISSUE THREAD

**Issue by Numerico** [CodigoSur/cyclope#46]
los botones de paginación son muy grandes y se caen a la línea siguiente en dispositivos pequeños

**Comment by MauHernandez** [comment]
Los botones de paginacion de que tipo? Luego de hacer varias pruebas veo un funcionamiento correcto, incluso para dimensiones de 320px de amplitud, lo cual es bastante bajo (adjunto imagen). Podrías por favor ofrecerme un ejemplo? Para enfocar mejor el problema.
![image](https://cloud.githubusercontent.com/assets/13241119/18994750/3d02b338-86f7-11e6-892a-04f7550f793f.png)

Gracias

**Comment by Numerico** [comment]
![paginacionbug](https://cloud.githubusercontent.com/assets/1114687/19446666/3d168e86-9470-11e6-8148-47f08383d99d.png)
la diferencia es que 'siguiente' y 'ultimo' ocupan mas espacio que 'next' y 'last'

**Comment by Numerico** [comment]
#91 resolves this
