### ISSUE TITLE
"The requested Folder does not exist."

### ISSUE THREAD

**Issue by altergui** [CodigoSur/cyclope#53]
Intentando agregar un documento

https://librerouter.org/admin/medialibrary/document/add/

cuando se abre el popup de filebrowser, tira el famoso warning "The requested Folder does not exist."

mirando el codigo, lo q esta pasando es q el javascript del boton apunta a:

href="javascript:FileBrowser.show('id_document', '/admin/filebrowser/browse/?pop=1&amp;dir=documents//2016/09&amp;type=Document');"

la carpeta /media/documents/2016/09 no existe (ni siquiera existe /media/documents realmente)

**Comment by Numerico** [comment]
Gui, y si intentas subirlo desde la Ventana Multimedia (ej. desde el artículo o campo de texto en que lo vas a insertar). Ésta crea las carpetas que no están. 
El FileBrowser no es lo suficientemente inteligente... la idea es pronto reemplazarlo totalmente por esta Ventana. 
No quita que mientras aún lo tengamos, hay que arreglar que sí lo haga, así es que dejo el issue abierto.

**Comment by Numerico** [comment]
viene de **lib/python2.7/site-packages/filebrowser/views.py**
