### ISSUE TITLE
Title que no se vea en home - Solo el nombre del sitio y no la descripcion completa

### ISSUE THREAD

**Issue by MauHernandez** [CodigoSur/cyclope#56]

**Comment by mezcalit** [comment]
He visto el issue y puedo decir que no es un bug actual en Cyclope-Bootstrap. 

Si se quiere que aparezca el title del "content" antes del title de la págin hay que sobreescribir el bloque title en el template del layout html correspondiente.

`{% block title %}{%if title %}{{title}} | {%endif%}{{ CYCLOPE_SITE_SETTINGS.global_title }}{%endblock%}`

Si no se quiere que aparezca el título del contenido antes del título de la página, entonces dejar como está. 

`{% block title %}{{ CYCLOPE_SITE_SETTINGS.global_title }}{%endblock%}`

Me parece que está bueno tenerlo claro, pero no es un issue por ahora. 
Aunque manejar mejor el tema de si aparece o no en las páginas internas el title del content creo que puede ser útil para indexación.

**Comment by MauHernandez** [comment]
Vale perfecto, lo puse en base a la reunión de esta manana que me comentaste que era un issue @mezcalit de todas maneras creo que es interesante ver el detalle de usar plantillas "desactualizadas" por asi decirlo, es decir, el conjunto de templates que empezamos a usar en pto viejo trae algunos detallitos que creo que debemos tenerlo presente para mejorar la creación de temas, estos templates deberían venir directamente del repo y no duplicar estos archivos, deberían heredar del tema madre por asi decirlo, de cyclope bootstrap y pisarlas solo si se necesita, saludos!
