### ISSUE TITLE
Documentación Crea tu Tema

### ISSUE THREAD

**Issue by mezcalit** [CodigoSur/cyclope#68]
Está desactualizado, hay que reescribir el procedimiento para que pueda haber una guía de creación de temas propios. Ya que es una de las lindas ventajas de CyclopeCMS, la facilidad con la que clonarte un tema y modificarlo a tu gusto. 
https://github.com/CodigoSur/cyclope/wiki/Crea-tu-Tema

**Comment by tian2992** [comment]
Considerar estrategias de crear temas.
Por ejemplo extender cyclopeproject para copiar una template con la cual iniciar.
Crear README en las templates.

**Comment by mezcalit** [comment]
He cambiado el título y mejorado la documentación aquí: 
https://github.com/CodigoSur/cyclope/wiki/Crear-un-tema-personalizado

**Comment by mezcalit** [comment]
He subido el custom_theme a github
https://github.com/CodigoSur/cyclope_custom_theme
