### ISSUE TITLE
actualizar comandos cyclope

### ISSUE THREAD

**Issue by Numerico** [CodigoSur/cyclope#71]
- cyclopeproject
- cyclopedemo
- borrar sitio demo/

**Comment by mezcalit** [comment]
para cyclopedemo hay que definir qué contenidos se crean. esa base de datos tiene que estar limpia. sin arrastres de cosas viejas. 
Creo que debería crearse un contenido de cada cosa, una colección, una categoría, un menú, unos ítems de menú. y el layout conifgurado para que muestre la categoría en la home.

**Comment by Numerico** [comment]
Ésto es exactamente lo que se crea https://github.com/CodigoSur/cyclope/blob/development/cyclope/management/commands/seed_data.py#L103
