### ISSUE TITLE
¿Problema de doble categorización?

### ISSUE THREAD

**Issue by mezcalit** [CodigoSur/cyclope#73]
Me ha pasado ya varias veces de ingresar a un artículo y ver que un contenido que categoricé se repite dos o más veces categorizado. Hoy me llamó la atención particularmente porque había borrado todas las categorizaciones de ese artículo, por lo que realmente se trata de un bug me parece. 

No he tenido tiempo de mirar a fondo el problema. Sin embargo hay que investigarlo, por eso abro el issue. Adjunto screen.

![error-doble-categorizacion](https://cloud.githubusercontent.com/assets/8534750/18439609/4ca5830c-78c3-11e6-90df-c18e764aeaf1.png)

**Comment by Numerico** [comment]
¿cómo reproducimos ésto?

**Comment by mezcalit** [comment]
Apenas me pase de nuevo lo reporto.
