### ISSUE TITLE
teaser view de staticpage está rota

### ISSUE THREAD

**Issue by mezcalit** [CodigoSur/cyclope#74]
La vista de teaser de páginas estáticas no se muestra como el resto de teasers de otros contenidos. 

**Así se ve el teaser de statipage:**

![teaser_staticpages](https://cloud.githubusercontent.com/assets/8534750/18444990/b7060892-78d8-11e6-857b-618815236d36.png)

**Así se ven los otros teasers:**

![teasers](https://cloud.githubusercontent.com/assets/8534750/18445005/c33044ca-78d8-11e6-8550-85c76c0290d4.png)

**Comment by Numerico** [comment]
Estoy reproduciendo esto pero:
¿De dónde sale la imágen de la Mona Lisa?
Quiero decir, las Páginas Estáticas no tienen imágen.
Intenté poniéndola en markitup con el widget, pero en este caso tampoco sale en el teaser.

**Comment by Numerico** [comment]
this was resolved in b221258
