### ISSUE TITLE
Problemas con API's en Redes Sociales.

### ISSUE THREAD

**Issue by ortegadaniel** [CodigoSur/cyclope#75]
Cuando compartes un articulo o cualquier otro contenido especificamente en Facebook, no toma en el resumen que genera facebook  la imagen correcta que deseamos. Tenemos casos de organizaciones que nos describen esto ya que en ocaciones no toma el logo de la organización al compartir sus sitios, sino cualquier otra imagen.

**Comment by santiagogarciagago** [comment]
@ortegadaniel  Eso ya está desarrollado en el sitio local nuevo de Radios Libres, habría que pasarlo al repo como algo propio de cyclope, son unas meta tags especiales. Y tendríamos que crear en los settings un tamaño especial de imagen para Facebook, ahora toma la big. 

Esto va de la mano con el plugin de Share que ahora no anda en Cyclope. Podemos convocar una mini-conversada para ver si lo que se hizo en ese sitio convence a todxs y yo podría asumir este ticket. 

```
<meta property="og:url" content="https://radioslibres.net/article/reproductor-html5-para-tu-radio-en-linea-en-5-paso/" />
<meta property="og:type" content="article" />
<meta property="og:title" content="REPRODUCTOR HTML5 PARA TU RADIO EN LÍNEA EN 5 PASOS" />
<meta property="og:description" content="Este _player_ es muy sencillo y versátil, sirve para redes sociales y navegadores de dispositivos móviles. 
" />
<meta property="og:site_name" content="RadiosLibres.net - https://radioslibres.net" />

<!-- Twitter Card data -->
<meta name="twitter:title" content="REPRODUCTOR HTML5 PARA TU RADIO EN LÍNEA EN 5 PASOS">
<meta name="twitter:url" content="https://radioslibres.net/article/reproductor-html5-para-tu-radio-en-linea-en-5-paso/" />
<meta name="twitter:description" content="Este _player_ es muy sencillo y versátil, sirve para redes sociales y navegadores de dispositivos móviles. 
" />
<meta name="twitter:creator" content="@radioslibres">

<!-- Open Graph Image -->
<meta property="og:image" content="https://radioslibres.net/media/pictures/2017/01/radio-en-liinea-html5_big.jpg" />
<meta name="twitter:image" content="https://radioslibres.net/media/pictures/2017/01/radio-en-liinea-html5_big.jpg">
```
