### ISSUE TITLE
link de imágenes de teasers roto

### ISSUE THREAD

**Issue by Numerico** [CodigoSur/cyclope#97]
en https://librerouter.org/team
los links de las fotos estan rotos, falta una comilla
```
<div class="teaser_icon_container hidden-xs">
     <a href="/article/cati/ title=" cati="" "="">
      <img class="teaser_icon img-responsive" src="/media/pictures/2016/09/cati_del_giorgio_0R2fOc2_medium.jpg" alt="Cati ">
     </a>
    </div>
```

**href="/article/cati/ title="**

ahi falta una comilla al final de cati/ (por ejemplo)
bueno, viendolo mejor hay una ensalada de comillas e iguales (=)

**Comment by altergui** [comment]
Lo mas curioso es que solo pasa con los "articulos"

En la portada http://librerouter.org/ se puede ver q los teaser de "documentos" (la Specifications Sheet v5 por ej) tienen el link de la imagen OK

Por otro lado, en el href roto, se puede ver una ensalada hecha con el "title", q quizas eche mas alguna pista

```
                <a href="/article/fire-grant-for-librerouter/ title=" fire="" grant"="">
                    <img class="teaser_icon img-responsive" src="/media/pictures/2016/11/fire_logo_medium.png" alt="FIRE Grant">
                </a>
```

eso que dice fire="" y grant"="" son las dos palabras (FIRE Grant) del title del articulo.

**Comment by mezcalit** [comment]
Hola Gui, gracias por este reporte. Estuve verificando el código y efectivamente fata el cierre de una etiqueta img en el archivo article_teaser.html en https://github.com/CodigoSur/cyclope/blob/development/cyclope/apps/articles/templates/articles/article_teaser.html apenas puedo comiteo el arreglo. ;)

**Comment by Numerico** [comment]
fixed  in 06f33de
