### ISSUE TITLE
Posibilidad de Edit desde el Media Widget

### ISSUE THREAD

**Issue by santiagogarciagago** [CodigoSur/cyclope#98]
Se podría añadir un botón que de acceso a la Edición de una imagen. Si subo o elijo una foto y me doy cuenta que puse mal el título tengo: o bien la borrro y subo de nuevo o bien abro una pestaña, voy a Pictures y allí edito la foto. Se podría colocar un botón en la pestaña x Delete (que pasaría a ser Delete / Edit) que permita editar la foto desde ahí. ¿Sería útil?

**Comment by mezcalit** [comment]
Creo que sería muy útil. Ya que verdaderamente con el media widget podemos ir pensando en acortar todo el trabajo de edición vía biblioteca multimedia.
